site_name: pyPRUF
repo_url: https://github.com/ashkihotah/pyPRUF
site_author: Nicolò Resta
theme:
  name: readthedocs
  highlightjs: true
nav:
  - Welcome to pyPRUF: index.md
  - User Guide: user_guide.md
  - About: about.md