site_name: pyPRUF
repo_url: https://github.com/ashkihotah/pyPRUF
site_author: Nicolò Resta
theme:
  name: readthedocs
  # highlightjs: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            # docstring_style: "google"
            # sort: source
            show_source: true
            show_root_heading: true
            separate_members: true

nav:
  - Welcome to pyPRUF: index.md
  - Getting Started:
    - Fuzzy Logic: fuzzy_logic.md
    - Fuzzy Relational Algebra: fuzzy_relational_algebra.md
    - PRUF Specific Operators: pruf_operators.md
  - API: api.md
  - About: about.md