name: Upload Python Package to PyPi

on:
  push:
    branches:
      - main
    tags:
      - 'v*' # Match tags starting with 'v'
      - '!v*-docs.*' # Exclude tags ending with "-docs.<number>"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11' # Replace with your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build

      - name: Build the package
        run: | # python setup.py sdist bdist_wheel
          python -m build

      - name: Publish to PyPI
        run: |
          twine upload dist/*
          echo "Successfully published to PyPI"
        env:
          TWINE_TOKEN: ${{ secrets.PYPI_TOKEN }}